### ISSUE TITLE
There is no 'dataset' file in the root directory.

### ISSUE THREAD

**Issue by LinkaSage** [Yukayo/MobGT#1]
Hello, this is a very impressive work. However, in your "README2.md" file, you mentioned that there is a 'dataset' file in the root directory to store the dataset. But I couldn't find it in the directory you shared. Could you please share the files in the 'dataset' directory, either using Google Drive or Baidu Netdisk? Thank you very much!

**Comment by Yukayo** [comment]
Hi, I uploaded the Gowalla dataset first and the Foursquare dataset is processing. As for the Toyota dataset, due to privacy, I can't make it public, hope you can understand it.

**Comment by LinkaSage** [comment]
Hi, thank you very much. I will be looking forward to your work!
