### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by xmai-hero** [Yukayo/MobGT#3]
作者您好，非常喜欢您的文章，但我发现代码中缺少对原始数据集的处理过程，请问可以分享一下吗？我想试一试在FoursquareNYC数据集上的结果如何？

**Comment by Yukayo** [comment]
处理程序上传了，源数据你找找yang dingqi的foursquare数据

**Comment by xmai-hero** [comment]
太感谢了！！非常感谢！！

**Comment by xmai-hero** [comment]
您上传的foursquare数据集处理代码我已成功运行，最后生成了5个csv文件和1个foursquare_nyc.pk文件，但随后我运行训练程序时意识到，训练代码读取的是经过进一步整合处理的train.pickle、train_idx.pkl、test.pickle、test_idx.pkl这四个文件，尽管我已经很努力的推测如何将预处理的数据集进一步整合，但还是失败了，所以想再次请求作者是否可以分享这部分的代码，这对我真的真的非常重要……

**Comment by Yukayo** [comment]
gen_pickles.py你去看看是不是这个，我上传了

**Comment by xmai-hero** [comment]
非常感谢，简单调试后已成功运行~
