### ISSUE TITLE
Some question about the datasets

### ISSUE THREAD

**Issue by CHULOKYEE** [Yukayo/MobGT#4]

**Comment by CHULOKYEE** [comment]
Hi, I am interested in your work! But when i try to reproduce the STAN, i found that can't preprocess the raw loc-gowalla_totalCheckins.txt(provided by stanford) in the load_gowalla.py. I wonder how to preprocess the raw .txt file and generate the .pkl file as requested in the train.py

**Comment by Yukayo** [comment]
https://github.com/yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation/tree/master/data
I suggest you can refer to this link which is the STAN's source code. You can analyze the structure of the .npy file first and then generate the .pkl file based on the .txt file.

**Comment by CHULOKYEE** [comment]
Thx for your prompt reply! One more question, i think the time format in raw .txt have to transfer into timestamp in gowalla.npy and the repeated location data have to delete in _poi.npy?

**Comment by Yukayo** [comment]
Sorry, I forget the preprocess of the STAN. But I think timestamp transfer is necessary, as for the repeated location, hmm I don't remember..... You can publish a new issue in the STAN source code.

**Comment by CHULOKYEE** [comment]
Thanks a lot~ Best wishes to you. :)
