### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Iscodebrid** [Yukayo/MobGT#5]
Hello, may I ask if you can share the other three datasets (in .pkl format) besides the NYC dataset?  (STAN processed)

**Comment by Yukayo** [comment]
I can't find them anymore, maybe you should report this issue in STAN's repository

**Comment by Iscodebrid** [comment]
Thank you for your response. I would like to know the details of your data processing, especially regarding the information about time intervals, when using STAN as a benchmark. Could you please provide some insights and details on how you processed the data? Additionally, your paper has been very inspiring to me. Thank you.

**Comment by Yukayo** [comment]
You should read this file carefully.
https://github.com/yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation/blob/master/load.py

**Comment by Iscodebrid** [comment]
> You should read this file carefully. https://github.com/yingtaoluo/Spatial-Temporal-Attention-Network-for-POI-Recommendation/blob/master/load.py

Thank you for your reply. I am confused about how the author created the .pkl files (such as NYC.pkl, Gowalla.pkl, TKY.pkl, or corresponding .npy files). This is making me feel quite puzzled.

**Comment by Yukayo** [comment]
Line 114 creates .pkl file. And you should refer to his .npy dataset file style, like each line is "POI, time, lat...", I mean this order, and you can make yourself .npy file.

**Comment by Iscodebrid** [comment]
> Line 114 creates .pkl file. And you should refer to his .npy dataset file style, like each line is "POI, time, lat...", I mean this order, and you can make yourself .npy file.

You're right. I also wanted to ask if you could provide the baseline_models_dataset in the MobGT project, if possible. The baseline model library you provided has been very helpful to me. Thank you very much.

**Comment by Yukayo** [comment]
I can't find them anymore
