### ISSUE TITLE
你好，能分享一下处理数据集的代码吗

### ISSUE THREAD

**Issue by yx-Feng** [Yukayo/MobGT#6]

**Comment by Yukayo** [comment]
我上传了process的代码啊

**Comment by yx-Feng** [comment]
> 我上传了process的代码啊
你好，是foursquare_process.py吗，这个好像只生成了几个graph.csv，划分数据集，生成train.pickle和test.pickle的是哪个文件啊，没找到😂

**Comment by Yukayo** [comment]
gen_pickles

**Comment by yx-Feng** [comment]
> gen_pickles

好的，谢谢你
